FROM openjdk:21-jdk-slim AS builder

WORKDIR /app

COPY ../config/build/libs/config.jar ./app.jar

FROM openjdk:21-jdk-slim

WORKDIR /app

RUN addgroup --system --gid 1001 appgroup

RUN adduser --system --uid 1001 --ingroup appgroup appuser

COPY --chown=appuser:appgroup --from=builder /app/app.jar ./app.jar
RUN chown -R appuser:appgroup /app

USER appuser
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
