name: 🛠️ Build and publish Docker images to GitHub Registry

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: 🛠️ Build and push Docker images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: 🧩 Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🧩 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 📲 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔨 Build and push Docker image (gateway)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.gateway
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gateway:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-gateway:latest

      - name: 🔨 Build and push Docker image (school-service)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.school-service
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-school-service:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-school-service:latest

      - name: 🔨 Build and push Docker image (student-service)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.student-service
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-student-service:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-student-service:latest
